# Generated by Django 3.2.9 on 2021-12-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='about_summary',
            field=models.TextField(blank=True),
        ),
    ]
