# Generated by Django 3.2.9 on 2021-12-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0002_myinfo_about_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='website_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
