# Generated by Django 3.2.9 on 2021-12-08 04:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webpages', '0002_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('comment', models.TextField()),
                ('is_postable', models.BooleanField(default=False)),
                ('reply', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('post_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.post')),
            ],
        ),
    ]
