# Generated by Django 3.2.9 on 2021-12-04 14:02

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', ckeditor.fields.RichTextField()),
                ('category', models.CharField(blank=True, max_length=255)),
                ('photo_home', models.ImageField(upload_to='media/home/%Y/%m')),
                ('photo_blogpage', models.ImageField(upload_to='media/blogpage/%Y/%m')),
                ('content', ckeditor.fields.RichTextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
